version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=testkey
      - DEBUG=1 
      - DB_NAME=value
      - DB_USER=value
      - DB_PASSWORD=value
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=value
      - POSTGRES_USER=TEST
      - POSTGRES_PASSWORD=TEST