version: '3.9'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn TakTask_project.wsgi -w 4 --bind 127.0.0.1:8001
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web