# Generated by Django 4.0.3 on 2022-03-19 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpentTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateField(blank=True, default=None, null=True)),
                ('spended', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('duedate', models.DateField(null=True)),
                ('estimate_time', models.IntegerField(blank=True, default=None, null=True)),
                ('If_Done', models.BooleanField(default=False)),
                ('time_spented_up', models.ManyToManyField(blank=True, related_name='time_spended', to='Task.spenttime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_describtion')),
            ],
        ),
    ]
