# Generated by Django 4.0.3 on 2022-03-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='spenttime',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
