# Generated by Django 4.0.3 on 2022-03-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_rename_donedate_task_donedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='DoneDate',
        ),
        migrations.AddField(
            model_name='task',
            name='Done_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
