# Generated by Django 4.0.3 on 2022-03-25 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('Task', '0007_remove_task_donedate_task_done_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='spenttime',
            name='related_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.team'),
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_describtion'),
        ),
    ]
