# Generated by Django 4.0.3 on 2022-03-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_spenttime_related_team_alter_spenttime_related_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spenttime',
            name='related_team',
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
