# Generated by Django 4.0.3 on 2022-03-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('Task', '0010_remove_spenttime_related_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='spenttime',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
        migrations.AddField(
            model_name='spenttime',
            name='related_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.team'),
        ),
        migrations.AddField(
            model_name='spenttime',
            name='related_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_describtion'),
        ),
    ]
