# Generated by Django 4.0.3 on 2022-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_spenttime_related_task_spenttime_related_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spenttime',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
