# Generated by Django 4.0.3 on 2022-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_spenttime_start_date_alter_spenttime_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spenttime',
            name='start_date',
        ),
        migrations.AddField(
            model_name='spenttime',
            name='start_time_hms',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='start_time',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
