# Generated by Django 4.0.3 on 2022-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0013_remove_spenttime_start_date_spenttime_start_time_hms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spenttime',
            name='start_time_hms',
        ),
        migrations.AddField(
            model_name='spenttime',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='spenttime',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
